apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Values.cronjob.deploymentName }}-cronjob
  namespace: {{ .Values.namespace }}
spec:
  schedule: {{ .Values.cronjob.schedule | quote }}
  concurrencyPolicy: {{ .Values.cronjob.concurrencyPolicy }}
  suspend: {{ .Values.cronjob.suspend }}
  successfulJobsHistoryLimit: {{ .Values.cronjob.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.cronjob.failedJobsHistoryLimit }}
  jobTemplate:
    spec:
      backoffLimit: {{ .Values.cronjob.backoffLimit }}
      ttlSecondsAfterFinished: {{ .Values.cronjob.ttlSecondsAfterFinished }}
      template:
        metadata:
          name: {{ .Values.cronjob.deploymentName }}-job
        spec:
          containers:
          - name: {{ .Values.cronjob.deploymentName }}
            image: {{ .Values.cronjob.image }}
            command: ["/bin/sh", "-c", "echo 'CronJob executed at '; date"]
            ports:
              {{- range .Values.deployment.containerPorts }}
              - containerPort: {{ . }}
              {{- end }}
            resources:
              limits:
                memory: {{ .Values.deployment.resources.limits.memory }}
                cpu: {{ .Values.deployment.resources.limits.cpu }}
              requests:
                memory: {{ .Values.deployment.resources.requests.memory }}
                cpu: {{ .Values.deployment.resources.requests.cpu }}
          restartPolicy: OnFailure
      parallelism: 1
