# Deployment definition used for managing component-specific pods
{{- range .Values.applications }}
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: {{ .name }}
  namespace: {{ $.Values.namespace }}
spec:
  replicas: {{ .replicas }}
  revisionHistoryLimit: {{ $.Values.deployment.revisionHistoryLimit }}
  selector:
    matchLabels:
      component: {{ .name }}
  template:
    metadata:
      labels:
        app: {{ $.Values.namespace }}
        component: {{ .name }}
      {{- if $.Values.vault.flags.vaultAgentInitEnabled }}
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/agent-init-first: 'true'
        vault.hashicorp.com/preserve-secret-case: 'true'
        vault.hashicorp.com/tls-secret: 'vault-tls-secret'
        vault.hashicorp.com/ca-cert: "/vault/tls/ca-bundle.crt"
        vault.hashicorp.com/log-level: '{{ $.Values.vault.configs.logLevel | default "debug" }}'
        vault.hashicorp.com/service: '{{ $.Values.vault.configs.vaultServer | default "https://VAULT_ADDR" }}'
        vault.hashicorp.com/namespace: '{{ $.Values.vault.configs.vaultNamespace | default "NAMESPACE" }}'
        vault.hashicorp.com/auth-type: 'kubernetes'
        vault.hashicorp.com/auth-path: 'auth/kubernetes/{{ $.Values.vault.configs.kubernetesCluster | default "KUBERNETES_CLUSTER" }}'
        vault.hashicorp.com/role: '{{ $.Values.vault.configs.vaultFolder | default "APPNAME.APPID" }}-kubernetes-role'
        vault.hashicorp.com/agent-inject-default-template: '{{ $.Values.vault.configs.outputFormat | default "json" }}'
        {{- range $.Values.vault.secrets }}
        vault.hashicorp.com/agent-inject-secret-{{ .secretFileName }}: '{{ .secretPath }}'
        vault.hashicorp.com/agent-inject-template-{{ .secretFileName }}: |
          {{`{{ with secret " `}} {{ .secretPath }} {{` " }}`} }
          {{`{{ .Data.data | toJSON }}`} }
          {{`{{ end }}`} }
        {{- end }}
      {{- end }}
    spec:
      serviceAccountName: vault-auth
      containers:
      - name: {{ .name }}
        image: {{ .image }}
        env:
          - name: ASPNETCORE_ENVIRONMENT
            value: {{ .env.ASPNETCORE_ENVIRONMENT }}
        ports:
          {{- range .containerPorts }}
          - containerPort: {{ . }}
          {{- end }}
        resources:
          limits:
            memory: {{ .resources.limits.memory }}
            cpu: {{ .resources.limits.cpu }}
          requests:
            memory: {{ .resources.requests.memory }}
            cpu: {{ .resources.requests.cpu }}
      imagePullSecrets:
        {{- range .imagePullSecrets }}
        - name: {{ . }}
        {{- end }}
---
{{- end }}
