{{- range .Values.applications }}
apiVersion: v1
kind: Service
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: {{ .name }}-svc
spec:
  ports:
    {{- range .service.ports }}
    - name: {{ .name }}
      port: {{ .port }}
      protocol: {{ .protocol }}
      targetPort: {{ .targetPort }}
    {{- end }}
  selector:
    component: {{ .name }}
---
{{- end }}
