# Namespace definition
namespace: valuestest

# Deployment vars
deployment:
  name: valuestest
  replicas: 1
  revisionHistoryLimit: 6
  image: nginx:latest
  containerPorts:
    - 5000 
  resources:
    limits:
      memory: "512Mi"
      cpu: "250m"
    requests:
      memory: "256Mi"
      cpu: "125m"

# Service vars
service:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80

